// Risk Scoring Weights & Thresholds

export const RISK_LEVELS = {
  LOW: "low",
  MEDIUM: "medium",
  HIGH: "high",
  CRITICAL: "critical",
} as const;

export const RISK_THRESHOLDS = {
  LOW_MAX: 24,
  MEDIUM_MAX: 49,
  HIGH_MAX: 74,
} as const;

export const RISK_WEIGHTS = {
  BASE_PAYMENT_FAILURE: 40,
  RETRY_ATTEMPT_MULTIPLIER: 10,
  ACTIVE_SUBSCRIPTION: 10,
  SUCCESSFUL_HISTORY_BONUS: 10,
  TEMPORARY_FAILURE_SURCHARGE: 10,
  ACTION_REQUIRED_FAILURE_SURCHARGE: 15,
  REPEATED_RECENT_FAILURES: 10,
} as const;

export const RECOVERABILITY_WEIGHTS = {
  BASE: 50,
  SUCCESSFUL_HISTORY_BONUS: 20,
  ACTIVE_SUBSCRIPTION_BONUS: 15,
  TEMPORARY_FAILURE_BONUS: 10,
  REPEATED_FAILURES_PENALTY: -20,
  CANCELLED_SUBSCRIPTION_PENALTY: -30,
} as const;
